package main

// Sourced from github.com/boyter/scc/blob/master/LANGUAGES.md

// Languages and extensions recognized as code
var langauges = map[string]string{
	".abap":           "ABAP",
	".abnf":           "ABNF",
	".as":             "ActionScript",
	".ada":            "Ada",
	".adb":            "Ada",
	".ads":            "Ada",
	".pad":            "Ada",
	".agda":           "Agda",
	".crn":            "Alchemist",
	".x":              "Alex",
	".als":            "Alloy",
	".aidl":           "Android Interface Definition Language",
	".apl":            "APL",
	".aplf":           "APL",
	".apln":           "APL",
	".aplc":           "APL",
	".dyalog":         "APL",
	".applescript":    "AppleScript",
	".art":            "Arturo",
	".adoc":           "AsciiDoc",
	".asa":            "ASP",
	".asp":            "ASP",
	".asax":           "ASP.NET",
	".ascx":           "ASP.NET",
	".asmx":           "ASP.NET",
	".aspx":           "ASP.NET",
	".master":         "ASP.NET",
	".sitemap":        "ASP.NET",
	".webinfo":        "ASP.NET",
	".s":              "Assembly",
	".asm":            "Assembly",
	".astro":          "Astro",
	".dats":           "ATS",
	".sats":           "ATS",
	".ats":            "ATS",
	".hats":           "ATS",
	".in":             "Autoconf",
	".ahk":            "AutoHotKey",
	".avdl":           "Avro",
	".avpr":           "Avro",
	".avsc":           "Avro",
	".awk":            "AWK",
	".bt":             "bait",
	".bash":           "BASH",
	".bash_login":     "BASH",
	".bash_logout":    "BASH",
	".bash_profile":   "BASH",
	".bashrc":         "BASH",
	".bas":            "Basic",
	".bat":            "Batch",
	".btm":            "Batch",
	".cmd":            "Batch",
	".bzl":            "Bazel",
	".build":          "Bazel",
	".workspace":      "Bazel",
	".bean":           "Bean",
	".beancount":      "Bean",
	".bicep":          "Bicep",
	".bb":             "Bitbake",
	".bbappend":       "Bitbake",
	".bbclass":        "Bitbake",
	".boo":            "Boo",
	".bsq":            "Bosque",
	".bf":             "Brainfuck",
	".bst":            "BuildStream",
	".c":              "C",
	".ec":             "C",
	".pgc":            "C",
	".h":              "C Header",
	".csh":            "C Shell",
	".cs":             "C#",
	".csx":            "C#",
	".cc":             "C++",
	".cpp":            "C++",
	".cxx":            "C++",
	".c++":            "C++",
	".pcc":            "C++",
	".ino":            "C++",
	".ccm":            "C++",
	".cppm":           "C++",
	".cxxm":           "C++",
	".c++m":           "C++",
	".mxx":            "C++",
	".hh":             "C++ Header",
	".hpp":            "C++ Header",
	".hxx":            "C++ Header",
	".inl":            "C++ Header",
	".ipp":            "C++ Header",
	".ixx":            "C++ Header",
	".cabal":          "Cabal",
	".cairo":          "Cairo",
	".cj":             "Cangjie",
	".capnp":          "Cap'n Proto",
	".cassius":        "Cassius",
	".ceylon":         "Ceylon",
	".chpl":           "Chapel",
	".circom":         "Circom",
	".prg":            "Clipper",
	".ch":             "Clipper",
	".clj":            "Clojure",
	".cljc":           "Clojure",
	".cljs":           "ClojureScript",
	".soy":            "Closure Template",
	".cmake":          "CMake",
	".cob":            "COBOL",
	".cbl":            "COBOL",
	".ccp":            "COBOL",
	".cobol":          "COBOL",
	".cpy":            "COBOL",
	".ql":             "CodeQL",
	".qll":            "CodeQL",
	".coffee":         "CoffeeScript",
	".cogent":         "Cogent",
	".cfm":            "ColdFusion",
	".cfc":            "ColdFusion CFScript",
	".v":              "Verilog",
	".creole":         "Creole",
	".cr":             "Crystal",
	".css":            "CSS",
	".csv":            "CSV",
	".cu":             "Cuda",
	".pyx":            "Cython",
	".pxi":            "Cython",
	".pxd":            "Cython",
	".d":              "D",
	".daml":           "DAML",
	".dart":           "Dart",
	".dts":            "Device Tree",
	".dtsi":           "Device Tree",
	".dhall":          "Dhall",
	".dm":             "DM",
	".dockerfile":     "Dockerfile",
	".dtd":            "Document Type Definition",
	".dot":            "DOT",
	".gv":             "DOT",
	".ex":             "Elixir",
	".exs":            "Elixir",
	".eex":            "Elixir Template",
	".elm":            "Elm",
	".ede":            "Emacs Dev Env",
	".el":             "Emacs Lisp",
	".emit":           "EmiT",
	".erl":            "Erlang",
	".hrl":            "Erlang",
	".exp":            "Expect",
	".xslt":           "Extensible Stylesheet Language Transformations",
	".xsl":            "Extensible Stylesheet Language Transformations",
	".fs":             "F#",
	".fsi":            "F#",
	".fsx":            "F#",
	".fsscript":       "F#",
	".fst":            "F*",
	".factor":         "Factor",
	".fnl":            "Fennel",
	".fidl":           "FIDL",
	".fish":           "Fish",
	".flow":           "Flow9",
	".4th":            "Forth",
	".forth":          "Forth",
	".fr":             "Forth",
	".frt":            "Forth",
	".fth":            "Forth",
	".f83":            "Forth",
	".fb":             "Forth",
	".fpm":            "Forth",
	".e4":             "Forth",
	".rx":             "Forth",
	".ft":             "Forth",
	".f":              "FORTRAN Legacy",
	".for":            "FORTRAN Legacy",
	".ftn":            "FORTRAN Legacy",
	".f77":            "FORTRAN Legacy",
	".pfo":            "FORTRAN Legacy",
	".f03":            "Fortran Modern",
	".f08":            "Fortran Modern",
	".f90":            "Fortran Modern",
	".f95":            "Fortran Modern",
	".fsh":            "Fragment Shader File",
	".ftl":            "Freemarker Template",
	".fsl":            "FSL",
	".fut":            "Futhark",
	".fxml":           "FXML",
	".gml":            "Game Maker Language",
	".yyp":            "Game Maker Project",
	".gd":             "GDScript",
	".gemfile":        "Gemfile",
	".feature":        "Gherkin Specification",
	".gleam":          "Gleam",
	".vert":           "GLSL",
	".tesc":           "GLSL",
	".tese":           "GLSL",
	".geom":           "GLSL",
	".frag":           "GLSL",
	".comp":           "GLSL",
	".glsl":           "GLSL",
	".gn":             "GN",
	".gni":            "GN",
	".go":             "Go",
	".tmpl":           "Go Template",
	".gohtml":         "Go Template",
	".gotxt":          "Go Template",
	".tscn":           "Godot Scene",
	".gradle":         "Gradle",
	".graphql":        "GraphQL",
	".groovy":         "Groovy",
	".grt":            "Groovy",
	".gtpl":           "Groovy",
	".gvy":            "Groovy",
	".gw":             "Gwion",
	".haml":           "HAML",
	".hamlet":         "Hamlet",
	".hbs":            "Handlebars",
	".handlebars":     "Handlebars",
	".y":              "Happy",
	".ly":             "Happy",
	".ha":             "Hare",
	".hs":             "Haskell",
	".hx":             "Haxe",
	".hcl":            "HCL",
	".heex":           "Phoenix LiveView",
	".hex":            "HEX",
	".hoon":           "hoon",
	".html":           "HTML",
	".htm":            "HTML",
	".idl":            "IDL",
	".webidl":         "IDL",
	".widl":           "IDL",
	".idr":            "Idris",
	".lidr":           "Idris",
	".ini":            "INI",
	".ihex":           "Intel HEX",
	".thy":            "Isabelle",
	".jade":           "Jade",
	".jai":            "JAI",
	".janet":          "Janet",
	".java":           "Java",
	".js":             "JavaScript",
	".mjs":            "JavaScript",
	".jsp":            "JavaServer Pages",
	".jenkinsfile":    "Jenkins Buildfile",
	".jinja":          "Jinja",
	".j2":             "Jinja",
	".jinja2":         "Jinja",
	".jq":             "jq",
	".json":           "JSON",
	".json5":          "JSON5",
	".jsonc":          "JSONC",
	".jsonl":          "JSONL",
	".jsonnet":        "Jsonnet",
	".libsonnet":      "Jsonnet",
	".jsx":            "JSX",
	".jl":             "Julia",
	".julius":         "Julius",
	".ipynb":          "Jupyter",
	".jpynb":          "Jupyter",
	".justfile":       "Just",
	".k":              "K",
	".ksh":            "Korn Shell",
	".kt":             "Kotlin",
	".kts":            "Kotlin",
	".lalrpop":        "LALRPOP",
	".tex":            "TeX",
	".lds":            "LD Script",
	".lean":           "Lean",
	".hlean":          "Lean",
	".less":           "LESS",
	".l":              "LEX",
	".license":        "License",
	".licence":        "License",
	".copying":        "License",
	".copying3":       "License",
	".unlicense":      "License",
	".unlicence":      "License",
	".license-apache": "License",
	".licence-apache": "License",
	".license-mit":    "License",
	".licence-mit":    "License",
	".copyright":      "License",
	".lisp":           "Lisp",
	".lsp":            "Lisp",
	".ls":             "LiveScript",
	".ll":             "LLVM IR",
	".lol":            "LOLCODE",
	".lols":           "LOLCODE",
	".lua":            "Lua",
	".luau":           "Luau",
	".lucius":         "Lucius",
	".luna":           "Luna",
	".m4":             "m4",
	".mxml":           "Macromedia eXtensible Markup Language",
	".mad":            "Madlang",
	".makefile":       "Makefile",
	".mak":            "Makefile",
	".mk":             "Makefile",
	".bp":             "Makefile",
	".gnumakefile":    "Makefile",
	".mako":           "Mako",
	".mao":            "Mako",
	".md":             "Markdown",
	".markdown":       "Markdown",
	".m":              "Objective C",
	".maxpat":         "Max",
	".mdx":            "MDX",
	".metal":          "Metal",
	".m3":             "Modula3",
	".mg":             "Modula3",
	".ig":             "Modula3",
	".i3":             "Modula3",
	".def":            "Module-Definition",
	".mc":             "Monkey C",
	".mbt":            "Moonbit",
	".mqh":            "MQL Header",
	".mq4":            "MQL4",
	".mq5":            "MQL5",
	".csproj":         "MSBuild",
	".vbproj":         "MSBuild",
	".fsproj":         "MSBuild",
	".vcproj":         "MSBuild",
	".vcxproj":        "MSBuild",
	".ilproj":         "MSBuild",
	".myapp":          "MSBuild",
	".props":          "MSBuild",
	".rdlc":           "MSBuild",
	".resx":           "MSBuild",
	".settings":       "MSBuild",
	".sln":            "MSBuild",
	".targets":        "MSBuild",
	".mps":            "MUMPS",
	".mustache":       "Mustache",
	".ndf":            "Nial",
	".nim":            "Nim",
	".nix":            "Nix",
	".nu":             "Nushell",
	".nuspec":         "nuspec",
	".mm":             "Objective C++",
	".ml":             "OCaml",
	".mli":            "OCaml",
	".odin":           "Odin",
	".opa":            "Opalang",
	".qasm":           "OpenQASM",
	".org":            "Org",
	".oz":             "Oz",
	".pas":            "Pascal",
	".patch":          "Patch",
	".pl":             "Perl",
	".pm":             "Perl",
	".leex":           "Phoenix LiveView",
	".php":            "PHP",
	".pi":             "Picat",
	".pkgbuild":       "PKGBUILD",
	".pkl":            "Pkl",
	".fnc":            "PL/SQL",
	".pkb":            "PL/SQL",
	".pks":            "PL/SQL",
	".prc":            "PL/SQL",
	".trg":            "PL/SQL",
	".vw":             "PL/SQL",
	".text":           "Plain Text",
	".txt":            "Plain Text",
	".polly":          "Polly",
	".pony":           "Pony",
	".ps1":            "Powershell",
	".psm1":           "Powershell",
	".pde":            "Processing",
	".p":              "Prolog",
	".pro":            "Prolog",
	".properties":     "Properties File",
	".proto":          "Protocol Buffers",
	".prql":           "PRQL",
	".psl":            "PSL Assertion",
	".pp":             "Puppet",
	".purs":           "PureScript",
	".py":             "Python",
	".pyw":            "Python",
	".pyi":            "Python",
	".qs":             "Q#",
	".qcl":            "QCL",
	".qml":            "QML",
	".r":              "R",
	".rkt":            "Racket",
	".rake":           "Rakefile",
	".rakefile":       "Rakefile",
	".raku":           "Raku",
	".rakumod":        "Raku",
	".rakutest":       "Raku",
	".rakudoc":        "Raku",
	".t":              "Raku",
	".cshtml":         "Razor",
	".razor":          "Razor",
	".re":             "ReasonML",
	".rei":            "ReasonML",
	".reds":           "Redscript",
	".rdl":            "Report Definition Language",
	".res":            "ReScript",
	".resi":           "ReScript",
	".rst":            "ReStructuredText",
	".robot":          "Robot Framework",
	".rb":             "Ruby",
	".rhtml":          "Ruby HTML",
	".erb":            "Ruby HTML",
	".rs":             "Rust",
	".sas":            "SAS",
	".sass":           "Sass",
	".scss":           "Sass",
	".sc":             "Scala",
	".scala":          "Scala",
	".scm":            "Scheme",
	".ss":             "Scheme",
	".csig":           "Scons",
	".sconstruct":     "Scons",
	".sconscript":     "Scons",
	".sed":            "sed",
	".sh":             "Shell",
	".sieve":          "Sieve",
	".il":             "SKILL",
	".slang":          "Slang",
	".slint":          "Slint",
	".tpl":            "Smarty Template",
	".smk":            "Snakemake",
	".rules":          "Snakemake",
	".snakefile":      "Snakemake",
	".sno":            "SNOBOL",
	".sbl":            "Softbridge Basic",
	".sol":            "Solidity",
	".spdx":           "SPDX",
	".e":              "Specman e",
	".ckt":            "Spice Netlist",
	".spl":            "SPL",
	".sql":            "SQL",
	".dml":            "SQL",
	".ddl":            "SQL",
	".dql":            "SQL",
	".srt":            "SRecode Template",
	".stan":           "Stan",
	".do":             "Stata",
	".ado":            "Stata",
	".styl":           "Stylus",
	".svelte":         "Svelte",
	".svg":            "SVG",
	".swift":          "Swift",
	".i":              "Swig",
	".automount":      "Systemd",
	".device":         "Systemd",
	".link":           "Systemd",
	".mount":          "Systemd",
	".path":           "Systemd",
	".scope":          "Systemd",
	".service":        "Systemd",
	".slice":          "Systemd",
	".socket":         "Systemd",
	".swap":           "Systemd",
	".target":         "Systemd",
	".timer":          "Systemd",
	".sv":             "SystemVerilog",
	".svh":            "SystemVerilog",
	".taskpaper":      "TaskPaper",
	".tcl":            "TCL",
	".teal":           "Teal",
	".templ":          "Templ",
	".tt":             "Treetop",
	".tt2":            "TemplateToolkit",
	".tera":           "Tera",
	".tf":             "Terraform",
	".sty":            "TeX",
	".textile":        "Textile",
	".thrift":         "Thrift",
	".tl":             "TL",
	".toml":           "TOML",
	".treetop":        "Treetop",
	".ttcn":           "TTCN-3",
	".ttcn3":          "TTCN-3",
	".ttcnpp":         "TTCN-3",
	".twig":           "Twig Template",
	".ts":             "TypeScript",
	".tsx":            "TypeScript",
	".tsp":            "TypeSpec",
	".typ":            "Typst",
	".uc":             "Unreal Script",
	".uci":            "Unreal Script",
	".upkg":           "Unreal Script",
	".up":             "Up",
	".ur":             "Ur/Web",
	".urs":            "Ur/Web",
	".urp":            "Ur/Web Project",
	".vala":           "Vala",
	".vcl":            "Varnish Configuration",
	".vg":             "Verilog",
	".vh":             "Verilog",
	".irunargs":       "Verilog Args File",
	".xrunargs":       "Verilog Args File",
	".vsh":            "Vertex Shader File",
	".vhd":            "VHDL",
	".vhdl":           "VHDL",
	".vim":            "Vim Script",
	".vimrc":          "Vim Script",
	".gvimrc":         "Vim Script",
	"._vimrc":         "Vim Script",
	"._gvimrc":        "Vim Script",
	".vb":             "Visual Basic",
	".cls":            "Visual Basic for Applications",
	".vue":            "Vue",
	".fgmj":           "W.I.S.E. Jobfile",
	".wsdl":           "Web Services Description Language",
	".wgsl":           "WebGPU Shading Language",
	".wy":             "wenyan",
	".rc":             "Windows Resource-Definition Script",
	".nb":             "Wolfram",
	".wl":             "Wolfram",
	".wren":           "Wren",
	".xaml":           "XAML",
	".xcconfig":       "Xcode Config",
	".xml":            "XML",
	".xsd":            "XML Schema",
	".xtend":          "Xtend",
	".yaml":           "YAML",
	".yml":            "YAML",
	".yarn":           "Yarn",
	".zig":            "Zig",
	".zok":            "ZoKrates",
	".zsh":            "Zsh",
	".zshenv":         "Zsh",
	".zlogin":         "Zsh",
	".zlogout":        "Zsh",
	".zprofile":       "Zsh",
	".zshrc":          "Zsh",
}

// Specific file names that are categorized as a particular language
var file_languages = map[string]string{
	".bash_login":             "BASH",
	".bash_logout":            "BASH",
	".bash_profile":           "BASH",
	".bashrc":                 "BASH",
	"build.bazel":             "Bazel",
	"bitbucket-pipelines.yml": "Bitbucket Pipeline",
	"blade.php":               "Blade template",
	".cshrc":                  "C Shell",
	"cmakelists.txt":          "CMake",
	".dockerignore":           "Docker ignore",
	".gitignore":              "gitignore",
	".ignore":                 "ignore",
	".kshrc":                  "Korn Shell",
	"meson.build":             "Meson",
	"meson_options.txt":       "Meson",
	"vcxproj.filters":         "MSBuild",
	".tcshrc":                 "Shell",
	"cs.st":                   "Smalltalk",
	"pck.st":                  "Smalltalk",
	"tf.json":                 "Terraform",
	"d.ts":                    "TypeScript Typings",
	".vimrc":                  "Vim Script",
	".gvimrc":                 "Vim Script",
	".zshenv":                 "Zsh",
	".zlogin":                 "Zsh",
	".zlogout":                "Zsh",
	".zprofile":               "Zsh",
	".zshrc":                  "Zsh",
}
